output: basic


features:
 lotsizesquarefeet: 1
 taxamount: 1

models:
 xgb: {'learning_rate':0.037,'max_depth':5,'subsample':0.8,'eval_metric':'mae','reg_lambda': 0.8, 'silent': 1,'reg_alpha': 0.4,'objective':'reg:linear'}
 lgb: {'learning_rate':0.0021,'boosting_type':'gbdt','objective': 'regression','metric': 'l1','sub_feature':0.5, 'bagging_fraction':0.85,'bagging_freq':40,'num_leaves':512,'min_data':500,'min_hessian':0.05,'verbose':0}
